package com.ucb.proyectofinal.core.data.db

import androidx.room.*
import com.ucb.proyectofinal.auth.data.dao.UserDao
import com.ucb.proyectofinal.auth.data.entity.UserEntity
import com.ucb.proyectofinal.lists.data.dao.ContentItemDao
import com.ucb.proyectofinal.lists.data.entity.ContentItemEntity
import com.ucb.proyectofinal.lists.data.dao.ContentListDao
import com.ucb.proyectofinal.lists.data.entity.ContentListEntity

@Database(
    entities = [ContentListEntity::class, ContentItemEntity::class, UserEntity::class],
    version = 4
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun contentListDao(): ContentListDao
    abstract fun contentItemDao(): ContentItemDao
    abstract fun userDao(): UserDao
}

// The Room KSP compiler generates the `actual` implementations for each target platform.
// Suppress the "no actual" warning — the actual will be generated by KSP before linking.
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}