package com.ucb.proyectofinal.core.data.db

import androidx.room.*

@Database(
    entities = [TodoEntity::class, ContentListEntity::class, ContentItemEntity::class],
    version = 2
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun getDao(): TodoDao
    abstract fun contentListDao(): ContentListDao
    abstract fun contentItemDao(): ContentItemDao
}

// The Room KSP compiler generates the `actual` implementations for each target platform.
// Suppress the "no actual" warning — the actual will be generated by KSP before linking.
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}