name: Deploy to Firebase App Distribution

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Create credentials file
        run: |
          echo "${{ secrets.CREDENTIAL_FILE_CONTENT }}" > google-services.json

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Upload to Firebase App Distribution
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: google-services.json
        run: ./gradlew :composeApp:appDistributionUploadRelease
